name: docker-image

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:

env:
  DOCKER_HUB_IMAGE_PREFIX: greenvine

jobs:
  lint_dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        dockerfile:
          - docker/base.Dockerfile
          - docker/node-builder.Dockerfile
    steps:
      - id: checkout_repo
        name: Checkout repository
        uses: actions/checkout@v2

      - id: lint_dockerfile
        name: Lint Dockerfile
        uses: brpaz/hadolint-action@v1.3.1
        with:
          dockerfile: ${{ matrix.dockerfile }}

  build_docker:
    name: Build and push images
    runs-on: ubuntu-20.04
    needs:
      - lint_dockerfile
    strategy:
      fail-fast: true
      matrix:
        dockerfile:
          - docker/base.Dockerfile
          - docker/node-builder.Dockerfile
        include:
          - dockerfile: docker/base.Dockerfile
            base_image: hey-grpc-base-builder
          - dockerfile: docker/node-builder.Dockerfile
            base_image: hey-grpc-nodejs-builder
    steps:
      - id: checkout_repo
        name: Checkout repository
        uses: actions/checkout@v2

      - id: login_docker_hub
        name: Login to Docker Hub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - id: gen_meta_for_docker_hub
        name: Generate meta for Docker Hub
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.DOCKER_HUB_IMAGE_PREFIX }}/${{ matrix.base_image }}
          tag-sha: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - id: build_push_to_docker_hub
        name: Build & push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.gen_meta_for_docker_hub.outputs.tags }}
          labels: ${{ steps.gen_meta_for_docker_hub.outputs.labels }}
