name: docker-image

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:

env:
  DOCKER_HUB_IMAGE_PREFIX: greenvine

jobs:
  lint_dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        dockerfile:
          - docker/base-builder.Dockerfile
          - docker/node-builder.Dockerfile
    steps:
      - id: checkout_repo
        name: Checkout repository
        uses: actions/checkout@v2

      - id: lint_dockerfile
        name: Lint Dockerfile
        uses: brpaz/hadolint-action@v1.3.1
        with:
          dockerfile: ${{ matrix.dockerfile }}

  build_docker:
    name: Build & Push Images
    runs-on: ubuntu-20.04
    needs:
      - lint_dockerfile
    steps:
      - id: checkout_repo
        name: Checkout repository
        uses: actions/checkout@v2

      - id: setup_qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - id: setup_docker_buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - id: get_commit_short_sha
        name: Get commit short SHA
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - id: login_docker_hub
        name: Login to Docker Hub
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - id: gen_base_meta_for_docker_hub
        name: Generate base image meta for Docker Hub
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.DOCKER_HUB_IMAGE_PREFIX }}/hey-grpc-base-builder
          tag-custom: commit-${{ steps.get_commit_short_sha.outputs.sha_short }}
          tag-sha: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - id: gen_nodejs_meta_for_docker_hub
        name: Generate Node.js image meta for Docker Hub
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.DOCKER_HUB_IMAGE_PREFIX }}/hey-grpc-nodejs-builder
          tag-custom: commit-${{ steps.get_commit_short_sha.outputs.sha_short }}
          tag-sha: false
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - id: build_push_base_to_docker_hub
        name: Build/Push base image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/base-builder.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: ENABLE_UPX=false
          tags: ${{ steps.gen_base_meta_for_docker_hub.outputs.tags }}
          labels: ${{ steps.gen_base_meta_for_docker_hub.outputs.labels }}

      - id: build_push_nodejs_to_docker_hub
        name: Build/Push Node.js image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/node-builder.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            BASE_IMAGE=${{ env.DOCKER_HUB_IMAGE_PREFIX }}/hey-grpc-base-builder
            BASE_IMAGE_TAG=commit-${{ steps.get_commit_short_sha.outputs.sha_short }}
            ENABLE_UPX=false
          tags: ${{ steps.gen_nodejs_meta_for_docker_hub.outputs.tags }}
          labels: ${{ steps.gen_nodejs_meta_for_docker_hub.outputs.labels }}
